# Number of simulated devices
countDevices = 10

# Will be used as name and c8y_Serial of the Device
deviceIdTemplate = "dev-serial-%05d"

# Interval in which the device shall send data
deviceSendingIntervalMs = 5000

# Time waited between adding new devices (per onboarding worker)
deviceAddWaitTimeMs = 100